use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricDefinition {
    pub id: String,
    pub metric: String,
    pub name: String,
    pub description: String,
    pub raw_value: String,
    pub low_risk: String,
    pub medium_risk: String,
    pub high_risk: String,
    pub hotspot_meaning: String,
}

pub fn metric_definitions() -> Vec<MetricDefinition> {
    vec![
        metric(
            "module_abstraction",
            "IIE",
            "Interface-to-Implementation Exposure",
            "Measures whether module interfaces expose too much surface relative to their implementation body.",
            "Median export complexity divided by implementation complexity across modules.",
            "<= 0.35",
            "> 0.35 and <= 0.80",
            "> 0.80",
            "Modules whose public surface is large relative to their implementation.",
        ),
        metric(
            "logic_cohesion",
            "EAD",
            "External Attribute Dependency",
            "Measures functions that read external object attributes more than local/self state, a feature-envy style cohesion signal.",
            "P90 of max(external parameter member reads - self member reads, 0) across functions.",
            "<= 1.0",
            "> 1.0 and <= 3.0",
            "> 3.0",
            "Functions that lean heavily on attributes of injected or parameter objects.",
        ),
        metric(
            "change_blast_radius",
            "TCR",
            "Transitive Change Radius",
            "Measures how many modules may be affected by changing a target module through reverse transitive dependencies.",
            "Maximum reverse reachable module ratio, excluding the target module itself.",
            "<= 0.10",
            "> 0.10 and <= 0.30",
            "> 0.30",
            "Modules with broad reverse dependency impact.",
        ),
        metric(
            "architecture_decoupling",
            "TCE",
            "Topological Cycle Entropy",
            "Measures architecture coupling from non-trivial dependency cycles.",
            "Largest non-trivial strongly connected component size divided by module count.",
            "<= 0.10",
            "> 0.10 and <= 0.30",
            "> 0.30",
            "Cycle-level hotspots are summarized at dimension level; inspect import cycles around coupled modules.",
        ),
        metric(
            "testability_pluggability",
            "EDR",
            "External Dependency Ratio",
            "Measures whether dependencies are injected instead of hardcoded, which affects testability and pluggability.",
            "Injected interactions divided by injected plus hardcoded interactions.",
            ">= 0.70",
            ">= 0.40 and < 0.70",
            "< 0.40",
            "Functions with hardcoded dependency pressure.",
        ),
        metric(
            "intent_redundancy",
            "PLME",
            "Path Length Meaning Entropy",
            "Measures import path ceremony and intent redundancy from deep relative import paths.",
            "Sum of relative parent traversals divided by unique import targets.",
            "<= 0.40",
            "> 0.40 and <= 1.20",
            "> 1.20",
            "Imports with deep relative path traversal.",
        ),
        metric(
            "state_encapsulation",
            "SSE+OA",
            "State Surface Expansion plus Ownership Ambiguity",
            "Measures mutable state expansion and ambiguous write ownership across modules.",
            "Object with sse = mutable declarations / mutated mutables, and oa = average multi-writer ambiguity.",
            "sse <= 1.10 and oa <= 0.10",
            "sse <= 1.60 and oa <= 0.35, unless one component is low",
            "sse > 1.60 or oa > 0.35",
            "Files with high mutable declaration expansion or entities written by multiple modules.",
        ),
        metric(
            "naming_clarity",
            "VND",
            "Vague Name Density",
            "Measures low-information naming tokens in files, directories, modules, functions, types, variables, and parameters.",
            "Weighted vague-token density across extracted names.",
            "<= 0.10",
            "> 0.10 and <= 0.25",
            "> 0.25",
            "Names containing vague tokens such as util, helper, common, manager, service, data, or index.",
        ),
        metric(
            "literal_consolidation",
            "LDP",
            "Literal Duplication Pressure",
            "Measures repeated string, template, and meaningful numeric literals that may represent unnamed domain concepts.",
            "Duplicate literal occurrences beyond the first divided by total interesting literals.",
            "<= 0.05",
            "> 0.05 and <= 0.15",
            "> 0.15",
            "Repeated literals that may deserve a named constant, enum, policy, or domain object.",
        ),
        metric(
            "directory_alignment",
            "DIS",
            "Directory/Import Skew",
            "Measures whether import edges respect the architecture implied by the directory tree and internal boundaries.",
            "Average import-edge score from directory distance, depth mismatch, and internal-boundary violations.",
            "<= 0.75",
            "> 0.75 and <= 1.50",
            "> 1.50",
            "Import edges that cut across distant directories or private internal structure.",
        ),
        metric(
            "module_reachability",
            "DMR",
            "Dead-End Module Ratio",
            "Measures modules that are not imported and are not obvious entry, test, or generated files.",
            "Unreferenced candidate modules divided by all non-entry, non-test, non-generated candidate modules.",
            "<= 0.20",
            "> 0.20 and <= 0.50",
            "> 0.50",
            "Modules that may be orphaned, stale, or outside the intended dependency graph.",
        ),
        metric(
            "behavior_mode_pressure",
            "BFP",
            "Boolean Flag Pressure",
            "Measures functions and call sites that encode multiple behavior modes through boolean-like flags.",
            "P90 weighted pressure from explicit boolean params, boolean defaults, naming heuristics, flag-controlled branches, multi-flag combinations, and boolean literal call args.",
            "<= 1.0",
            "> 1.0 and <= 3.0",
            "> 3.0",
            "Functions with boolean mode evidence or call sites passing true/false literals.",
        ),
    ]
}

#[expect(
    clippy::too_many_arguments,
    reason = "metric definitions are static schema entries with parallel text fields"
)]
fn metric(
    id: &str,
    metric: &str,
    name: &str,
    description: &str,
    raw_value: &str,
    low_risk: &str,
    medium_risk: &str,
    high_risk: &str,
    hotspot_meaning: &str,
) -> MetricDefinition {
    MetricDefinition {
        id: id.to_string(),
        metric: metric.to_string(),
        name: name.to_string(),
        description: description.to_string(),
        raw_value: raw_value.to_string(),
        low_risk: low_risk.to_string(),
        medium_risk: medium_risk.to_string(),
        high_risk: high_risk.to_string(),
        hotspot_meaning: hotspot_meaning.to_string(),
    }
}
